#
#$$$$$$$$\                   $$\      $$$$$$\             $$\     $$\ $$$$$$$$\ $$$$$$$\  $$\   $$\ $$\ $$\ $$\
#$$  _____|                  $$ |    $$  __$$\            $$ |    \__|\__$$  __|$$  __$$\ $$ | $$  |\__|$$ |$$ |
#$$ |   $$$$$$\   $$$$$$$\ $$$$$$\   $$ /  $$ |$$$$$$$\ $$$$$$\   $$\    $$ |   $$ |  $$ |$$ |$$  / $$\ $$ |$$ |
#$$$$$\ \____$$\ $$  _____|\_$$  _|  $$$$$$$$ |$$  __$$\\_$$  _|  $$ |   $$ |   $$$$$$$  |$$$$$  /  $$ |$$ |$$ |
#$$  __|$$$$$$$ |\$$$$$$\    $$ |    $$  __$$ |$$ |  $$ | $$ |    $$ |   $$ |   $$  ____/ $$  $$<   $$ |$$ |$$ |
#$$ |  $$  __$$ | \____$$\   $$ |$$\ $$ |  $$ |$$ |  $$ | $$ |$$\ $$ |   $$ |   $$ |      $$ |\$$\  $$ |$$ |$$ |
#$$ |  \$$$$$$$ |$$$$$$$  |  \$$$$  |$$ |  $$ |$$ |  $$ | \$$$$  |$$ |   $$ |   $$ |      $$ | \$$\ $$ |$$ |$$ |
#\__|   \_______|\_______/    \____/ \__|  \__|\__|  \__|  \____/ \__|   \__|   \__|      \__|  \__|\__|\__|\__|
################################################################################################################
#This plugin is made by SkyfightTV for everyone
#It works between spigot version 1.7 and 1.18
#This plugin can be reloaded

#Time during which the player is invulnerable after a teleportation in seconds.
time: 5

